trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: 'publish'

stages:
- stage: Build
  displayName: Build and package
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: Use .NET 8 SDK
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-c $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --logger trx'

    - task: DotNetCoreCLI@2
      displayName: Publish web app
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/ArkhamChangeRequest.csproj'
        arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/$(outputDir)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/$(outputDir)'
        artifactName: 'drop'

# To enable deployment, add a Deploy stage and set azureSubscription to your service connection
# and appName to your Azure Web App name, e.g.:
#- stage: Deploy
#  dependsOn: Build
#  jobs:
#  - job: DeployWebApp
#    steps:
#    - download: current
#      artifact: drop
#    - task: AzureWebApp@1
#      inputs:
#        azureSubscription: '<your-service-connection-name>'
#        appType: 'webApp'
#        appName: 'arkham-change'
#        package: '$(Pipeline.Workspace)/drop/*.zip'
